### PR TITLE
Enable maven releases

### PR DESCRIPTION
**Pull request by lmineiro**
And publishing to maven central

### CODE REVIEW

**Review by jbellmann — APPROVED** [review]
👍 

If you have to release more artefacts in this organization consider moving the 'custom-release' profile into a parent-pom for your organization as we did for 'stups' , to avoid copy paste and bloat the pom.xml for every single project.

**Comment by jbellmann** [comment]
👍 

And this is for zappr only ;-)

**Comment by lmineiro** [comment]
👍

**Comment by jbellmann** [comment]
hmm, seems to me I'm not able to approve for zappr. Let's try again

**Comment by jbellmann** [comment]
👍

**Comment by jbellmann** [comment]
Or zappr dont like comments ;-)
´

**Pull request merged**
